### 🤖 Guía de Asistencia con IA: Estandarización y Codificación de Variables (Feature Engineering)

En esta notebook, utilizaremos la Inteligencia Artificial como copiloto de aprendizaje. Aquí tienes algunas sugerencias de cómo interactuar con un asistente de IA (como Gemini o ChatGPT):

- **Elegir Encoding**: Pídele consejo: *'Tengo una variable categórica 'Ciudad' con 30 valores únicos. ¿Es mejor usar One-Hot Encoding o Target Encoding? ¿Cómo lo hago con scikit-learn?'*.
- **Cuándo escalar**: Pregúntale: *'¿Por qué los modelos basados en distancia (como KNN o SVM) necesitan que los datos estén estandarizados, y por qué a los árboles de decisión no les afecta?'*.

# Programa Ingenias+ Data Science

Ya dijimos previamente que un proyecto de data science tiene varias etapas:

1. Recolección de Datos
2. Exploración y Procesamiento de los datos
3. Modelado
4. Puesta en Producción

En la clase anterior, hicimos el analisis exploratorio de los datos y pudimos observar el tipo de datos que teniamos. Pudimos hacernos preguntas y ver algunos patrones. Todo ese conocimiento que adquirimos es útil para llevar a cabo la próxima parte de esta etapa: el procesamiento de los datos.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

<font size=5>  🚀 Procesamiento de datos 👩🏽‍💻</font>

Una vez que visualizamos y exploramos el dataset tenemos una idea de como lucen nuestros datos. Es por eso que ahora debemos empezar a preparar nuestros datos para los siguientes pasos según lo que aprendimos de ellos y las preguntas que nos planteamos.

In [ ]:
blackfriday = pd.read_csv('https://raw.githubusercontent.com/BelenUrdangarin/Entregables---Urdangarin/refs/heads/main/black_friday_reducido.csv', sep=';')
blackfriday.head(10)

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00248942,F,15.0,NaN,A,2,0,1,6.0,14.0,15200.0
1,1000001,P00087842,NaN,15.0,10.0,A,2,0,12,NaN,NaN,1422.0
2,1000001,P00085442,F,15.0,10.0,A,2,0,12,14.0,NaN,1057.0
3,1000003,P00193542,M,28.0,15.0,A,3,0,1,2.0,NaN,15227.0
4,1000004,P0097242,M,48.0,NaN,B,2,1,1,16.0,NaN,15686.0
5,1000005,P00251242,M,26.0,20.0,A,1,1,5,11.0,NaN,5254.0
6,1000006,P00190242,F,53.0,9.0,A,1,0,4,5.0,NaN,2079.0
7,1000008,P00249542,M,27.0,12.0,C,4,1,1,5.0,15.0,19614.0
8,1000008,P00214442,M,33.0,12.0,C,4,1,8,NaN,NaN,5982.0
9,1000009,P00135742,M,30.0,17.0,C,0,0,6,8.0,NaN,16662.0

#### 1) TRANSFORMACION DE VARIABLES

- La mayoría de los algoritmos de machine learning no admiten `strings` como variables y requieren que las variables sean numericas. Por ese motivo, es necesario convertir las variables categoricas en su representación numerica. Para esto hay varias opciones que iremos viendo.

**`LabelEncoder()`**

In [ ]:
from sklearn.preprocessing import LabelEncoder # Con Label encoder lo que hacemos es cambiar una categoria que tenia nombre por ejemplo de ciudades en que las ponga 0,1,2,3, ect

In [ ]:
test_encoder = LabelEncoder() #Ejecutamos la función

In [ ]:
blackfriday.loc[:, 'City_Category'] = test_encoder.fit_transform(blackfriday['City_Category']) ##mal porque estoy encodeando una variable predictiva

In [ ]:
blackfriday.head(10)

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00248942,F,15.0,NaN,0,2,0,1,6.0,14.0,15200.0
1,1000001,P00087842,NaN,15.0,10.0,0,2,0,12,NaN,NaN,1422.0
2,1000001,P00085442,F,15.0,10.0,0,2,0,12,14.0,NaN,1057.0
3,1000003,P00193542,M,28.0,15.0,0,3,0,1,2.0,NaN,15227.0
4,1000004,P0097242,M,48.0,NaN,1,2,1,1,16.0,NaN,15686.0
5,1000005,P00251242,M,26.0,20.0,0,1,1,5,11.0,NaN,5254.0
6,1000006,P00190242,F,53.0,9.0,0,1,0,4,5.0,NaN,2079.0
7,1000008,P00249542,M,27.0,12.0,2,4,1,1,5.0,15.0,19614.0
8,1000008,P00214442,M,33.0,12.0,2,4,1,8,NaN,NaN,5982.0
9,1000009,P00135742,M,30.0,17.0,2,0,0,6,8.0,NaN,16662.0

**`get_dummies()`**

In [ ]:
pd.get_dummies(blackfriday["Gender"]) ##falta el drop first y si quiero 1 y 0 el dtype int

            F      M
0        True  False
1       False  False
2        True  False
3       False   True
4       False   True
...       ...    ...
188318  False   True
188319  False   True
188320  False   True
188321  False   True
188322  False   True

[188323 rows x 2 columns]

In [ ]:
blackfriday[['female', 'male']] = pd.get_dummies(blackfriday["Gender"])

In [ ]:
blackfriday.head()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,female,male
0,1000001,P00248942,F,15.0,NaN,0,2,0,1,6.0,14.0,15200.0,True,False
1,1000001,P00087842,NaN,15.0,10.0,0,2,0,12,NaN,NaN,1422.0,False,False
2,1000001,P00085442,F,15.0,10.0,0,2,0,12,14.0,NaN,1057.0,True,False
3,1000003,P00193542,M,28.0,15.0,0,3,0,1,2.0,NaN,15227.0,False,True
4,1000004,P0097242,M,48.0,NaN,1,2,1,1,16.0,NaN,15686.0,False,True

**`OneHotEncoder()`**

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
blackfriday['Gender'].unique()

array(['F', nan, 'M'], dtype=object)

In [ ]:
gender_encoder = OneHotEncoder() ##si hago drop first despues no puede pedir categorias

In [ ]:
gender_encoder.fit_transform(blackfriday[['Gender']]).toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [ ]:
gender_encoder.categories_

[array(['F', 'M', nan], dtype=object)]

In [ ]:
niveles = gender_encoder.categories_[0].tolist() ##get_features_name_out

In [ ]:
one_hot_gender = pd.DataFrame(gender_encoder.fit_transform(blackfriday[['Gender']]).toarray(), columns=niveles)

In [ ]:
one_hot_gender

          F    M  NaN
0       1.0  0.0  0.0
1       0.0  0.0  1.0
2       1.0  0.0  0.0
3       0.0  1.0  0.0
4       0.0  1.0  0.0
...     ...  ...  ...
188318  0.0  1.0  0.0
188319  0.0  1.0  0.0
188320  0.0  1.0  0.0
188321  0.0  1.0  0.0
188322  0.0  1.0  0.0

[188323 rows x 3 columns]

In [ ]:
new_df = pd.concat([blackfriday, one_hot_gender], axis=1)

In [ ]:
new_df.head()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,female,male,F,M,NaN
0,1000001,P00248942,F,15.0,NaN,0,2,0,1,6.0,14.0,15200.0,True,False,1.0,0.0,0.0
1,1000001,P00087842,NaN,15.0,10.0,0,2,0,12,NaN,NaN,1422.0,False,False,0.0,0.0,1.0
2,1000001,P00085442,F,15.0,10.0,0,2,0,12,14.0,NaN,1057.0,True,False,1.0,0.0,0.0
3,1000003,P00193542,M,28.0,15.0,0,3,0,1,2.0,NaN,15227.0,False,True,0.0,1.0,0.0
4,1000004,P0097242,M,48.0,NaN,1,2,1,1,16.0,NaN,15686.0,False,True,0.0,1.0,0.0

**`binning`**

In [ ]:
print(blackfriday.Age.min())
print(blackfriday.Age.max())

14.0
74.0

In [ ]:
blackfriday["Age"] = pd.to_numeric(blackfriday["Age"], errors='coerce')

In [ ]:
bin_age = [10, 17, 70, 80]
labels = ["Adolescente", "Adulto", "Anciano"]

age_categories = pd.cut(blackfriday["Age"], bins=bin_age, labels=labels)

In [ ]:
age_categories

0         Adolescente
1         Adolescente
2         Adolescente
3              Adulto
4              Adulto
             ...
188318         Adulto
188319         Adulto
188320         Adulto
188321         Adulto
188322         Adulto
Name: Age, Length: 188323, dtype: category
Categories (3, object): ['Adolescente' < 'Adulto' < 'Anciano']